spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: alvin
    password: alvin
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: oracle
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
server:
  port: 9090